---
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 100
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- build/**/*
- docs/**/*
- tests/**/*
- vendor/**/*
