PHP: true

exclude_paths:
- build/**/*
- docs/**/*
- tests/**/*
- vendor/**/*

engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 100
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
