language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_script:
  - composer install
script:
  - mkdir -p build
  - vendor/bin/phpunit --coverage-clover build/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
