language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
before_script:
  - composer self-update
  - composer require codeclimate/php-test-reporter --dev
  - composer require sensiolabs/security-checker --dev
  - composer require satooshi/php-coveralls --dev
  - composer install
script:
  - mkdir -p build
  - vendor/bin/phpunit --coverage-clover build/clover.xml
  - vendor/bin/security-checker security:check
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
  - vendor/bin/test-reporter --coverage-report=build/clover.xml
  - vendor/bin/coveralls
addons:
  code_climate:
    repo_token: 6e2dc2ae362276a9f3f740a8d90d3b00f076416dc8091366adb049d8db37551e
notifications:
  email: false
